set(CPACK_PACKAGE_VENDOR Gerbera)
set(CPACK_PACKAGE_NAME gerbera)
set(CPACK_PACKAGE_CONTACT "Team Gerbera")
set(CPACK_PACKAGE_VERSION ${GERBERA_VERSION})
set(CPACK_STRIP_FILES YES)

# Debian Specifics
set(CPACK_DEBIAN_PACKAGE_SHLIBDEP ON) # Discover Deps
set(CPACK_DEBIAN_PACKAGE_SECTION "net")
set(CPACK_DEBIAN_COMPRESSION_TYPE "xz")

include(CPack)
